// dart format width=80
import 'package:drift/src/runtime/query_builder/query_builder.dart' as i2;
import 'dart:typed_data' as i3;
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class ConversationRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ConversationRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<bool> isPinned = GeneratedColumn<bool>(
    'is_pinned',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'CHECK ("is_pinned" IN (0, 1))',
    ),
    defaultValue: const Constant(false),
  );
  late final GeneratedColumn<String> assistantId = GeneratedColumn<String>(
    'assistant_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> truncateIndex = GeneratedColumn<int>(
    'truncate_index',
    aliasedName,
    false,
    check: () => i2.ComparableExpr(truncateIndex).isBiggerOrEqualValue(-1),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    defaultValue: const Constant(-1),
  );
  late final GeneratedColumn<String> versionSelectionsJson =
      GeneratedColumn<String>(
        'version_selections_json',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        defaultValue: const Constant('{}'),
      );
  late final GeneratedColumn<String> summary = GeneratedColumn<String>(
    'summary',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> lastSummarizedMessageCount =
      GeneratedColumn<int>(
        'last_summarized_message_count',
        aliasedName,
        false,
        check: () => i2.ComparableExpr(
          lastSummarizedMessageCount,
        ).isBiggerOrEqualValue(0),
        type: DriftSqlType.int,
        requiredDuringInsert: false,
        defaultValue: const Constant(0),
      );
  late final GeneratedColumn<String> chatSuggestionsJson =
      GeneratedColumn<String>(
        'chat_suggestions_json',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        defaultValue: const Constant('[]'),
      );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    title,
    createdAt,
    updatedAt,
    isPinned,
    assistantId,
    truncateIndex,
    versionSelectionsJson,
    summary,
    lastSummarizedMessageCount,
    chatSuggestionsJson,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'conversation_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  ConversationRows createAlias(String alias) {
    return ConversationRows(attachedDatabase, alias);
  }
}

class MessageRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MessageRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> conversationId = GeneratedColumn<String>(
    'conversation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'REFERENCES conversation_rows (id) ON DELETE CASCADE',
    ),
  );
  late final GeneratedColumn<String> role = GeneratedColumn<String>(
    'role',
    aliasedName,
    false,
    check: () => role.isNotValue(''),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> content = GeneratedColumn<String>(
    'content',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> timestamp = GeneratedColumn<int>(
    'timestamp',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> modelId = GeneratedColumn<String>(
    'model_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> providerId = GeneratedColumn<String>(
    'provider_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> totalTokens = GeneratedColumn<int>(
    'total_tokens',
    aliasedName,
    true,
    check: () => i2.ComparableExpr(totalTokens).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<bool> isStreaming = GeneratedColumn<bool>(
    'is_streaming',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'CHECK ("is_streaming" IN (0, 1))',
    ),
    defaultValue: const Constant(false),
  );
  late final GeneratedColumn<String> reasoningText = GeneratedColumn<String>(
    'reasoning_text',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> reasoningStartAt = GeneratedColumn<int>(
    'reasoning_start_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> reasoningFinishedAt = GeneratedColumn<int>(
    'reasoning_finished_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> translation = GeneratedColumn<String>(
    'translation',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> reasoningSegmentsJson =
      GeneratedColumn<String>(
        'reasoning_segments_json',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
      );
  late final GeneratedColumn<String> groupId = GeneratedColumn<String>(
    'group_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> turnId = GeneratedColumn<String>(
    'turn_id',
    aliasedName,
    false,
    check: () => turnId.isNotValue(''),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> generationStatus = GeneratedColumn<String>(
    'generation_status',
    aliasedName,
    false,
    check: () => generationStatus.isIn(const {
      'draft',
      'completed',
      'interrupted',
      'failed',
    }),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> version = GeneratedColumn<int>(
    'version',
    aliasedName,
    false,
    check: () => i2.ComparableExpr(version).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    defaultValue: const Constant(0),
  );
  late final GeneratedColumn<int> promptTokens = GeneratedColumn<int>(
    'prompt_tokens',
    aliasedName,
    true,
    check: () => i2.ComparableExpr(promptTokens).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> completionTokens = GeneratedColumn<int>(
    'completion_tokens',
    aliasedName,
    true,
    check: () => i2.ComparableExpr(completionTokens).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> cachedTokens = GeneratedColumn<int>(
    'cached_tokens',
    aliasedName,
    true,
    check: () => i2.ComparableExpr(cachedTokens).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> durationMs = GeneratedColumn<int>(
    'duration_ms',
    aliasedName,
    true,
    check: () => i2.ComparableExpr(durationMs).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> messageOrder = GeneratedColumn<int>(
    'message_order',
    aliasedName,
    false,
    check: () => i2.ComparableExpr(messageOrder).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    conversationId,
    role,
    content,
    timestamp,
    modelId,
    providerId,
    totalTokens,
    isStreaming,
    reasoningText,
    reasoningStartAt,
    reasoningFinishedAt,
    translation,
    reasoningSegmentsJson,
    groupId,
    turnId,
    generationStatus,
    version,
    promptTokens,
    completionTokens,
    cachedTokens,
    durationMs,
    messageOrder,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'message_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {conversationId, messageOrder},
    {conversationId, groupId, version},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  MessageRows createAlias(String alias) {
    return MessageRows(attachedDatabase, alias);
  }
}

class TurnRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TurnRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> conversationId = GeneratedColumn<String>(
    'conversation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'REFERENCES conversation_rows (id) ON DELETE CASCADE',
    ),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [id, conversationId, createdAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'turn_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  TurnRows createAlias(String alias) {
    return TurnRows(attachedDatabase, alias);
  }
}

class ConversationMcpServerRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ConversationMcpServerRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> conversationId = GeneratedColumn<String>(
    'conversation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'REFERENCES conversation_rows (id) ON DELETE CASCADE',
    ),
  );
  late final GeneratedColumn<String> serverId = GeneratedColumn<String>(
    'server_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> ordinal = GeneratedColumn<int>(
    'ordinal',
    aliasedName,
    false,
    check: () => i2.ComparableExpr(ordinal).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [conversationId, serverId, ordinal];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'conversation_mcp_server_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {conversationId, serverId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {conversationId, ordinal},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  ConversationMcpServerRows createAlias(String alias) {
    return ConversationMcpServerRows(attachedDatabase, alias);
  }
}

class ToolEventRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ToolEventRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> messageId = GeneratedColumn<String>(
    'message_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'REFERENCES message_rows (id) ON DELETE CASCADE',
    ),
  );
  late final GeneratedColumn<String> eventsJson = GeneratedColumn<String>(
    'events_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [messageId, eventsJson];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'tool_event_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {messageId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  ToolEventRows createAlias(String alias) {
    return ToolEventRows(attachedDatabase, alias);
  }
}

class GeminiThoughtSignatureRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  GeminiThoughtSignatureRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> messageId = GeneratedColumn<String>(
    'message_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'REFERENCES message_rows (id) ON DELETE CASCADE',
    ),
  );
  late final GeneratedColumn<String> signature = GeneratedColumn<String>(
    'signature',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [messageId, signature];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'gemini_thought_signature_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {messageId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  GeminiThoughtSignatureRows createAlias(String alias) {
    return GeminiThoughtSignatureRows(attachedDatabase, alias);
  }
}

class ChatStorageMetaRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ChatStorageMetaRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> key = GeneratedColumn<String>(
    'key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
    'value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [key, value];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'chat_storage_meta_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {key};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  ChatStorageMetaRows createAlias(String alias) {
    return ChatStorageMetaRows(attachedDatabase, alias);
  }
}

class MessagePartRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MessagePartRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> conversationId = GeneratedColumn<String>(
    'conversation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> revisionId = GeneratedColumn<String>(
    'revision_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> ordinal = GeneratedColumn<int>(
    'ordinal',
    aliasedName,
    false,
    check: () => i2.ComparableExpr(ordinal).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> kind = GeneratedColumn<String>(
    'kind',
    aliasedName,
    false,
    check: () =>
        kind.isIn(const ['text', 'reasoning', 'tool_call', 'tool_result']),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> payload = GeneratedColumn<String>(
    'payload',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    conversationId,
    revisionId,
    ordinal,
    kind,
    payload,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'message_part_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {revisionId, ordinal};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {conversationId, revisionId, ordinal},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  MessagePartRows createAlias(String alias) {
    return MessagePartRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (revision_id) REFERENCES message_rows (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED',
    'CHECK (updated_at >= created_at)',
  ];
}

class ProviderArtifactRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  ProviderArtifactRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> conversationId = GeneratedColumn<String>(
    'conversation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> revisionId = GeneratedColumn<String>(
    'revision_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> kind = GeneratedColumn<String>(
    'kind',
    aliasedName,
    false,
    check: () => kind.isNotValue(''),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> payload = GeneratedColumn<String>(
    'payload',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    conversationId,
    revisionId,
    kind,
    payload,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'provider_artifact_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {revisionId, kind};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  ProviderArtifactRows createAlias(String alias) {
    return ProviderArtifactRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (revision_id) REFERENCES message_rows (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED',
    'CHECK (updated_at >= created_at)',
  ];
}

class MigrationRunRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MigrationRunRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> sourceKind = GeneratedColumn<String>(
    'source_kind',
    aliasedName,
    false,
    check: () => sourceKind.isIn(const ['hive', 'legacy_json']),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> sourceHash = GeneratedColumn<String>(
    'source_hash',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    check: () => status.isIn(const ['building', 'completed', 'failed']),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> startedAt = GeneratedColumn<int>(
    'started_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> completedAt = GeneratedColumn<int>(
    'completed_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    sourceKind,
    sourceHash,
    status,
    startedAt,
    completedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'migration_run_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {sourceKind, sourceHash},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  MigrationRunRows createAlias(String alias) {
    return MigrationRunRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'CHECK (completed_at IS NULL OR completed_at >= started_at)',
  ];
}

class MigrationIssueRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  MigrationIssueRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> migrationRunId = GeneratedColumn<String>(
    'migration_run_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'REFERENCES migration_run_rows (id) ON DELETE CASCADE',
    ),
  );
  late final GeneratedColumn<String> conversationId = GeneratedColumn<String>(
    'conversation_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> sourceEntityId = GeneratedColumn<String>(
    'source_entity_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> kind = GeneratedColumn<String>(
    'kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> severity = GeneratedColumn<String>(
    'severity',
    aliasedName,
    false,
    check: () => severity.isIn(const ['warning', 'recovered', 'rejected']),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> detailsJson = GeneratedColumn<String>(
    'details_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    defaultValue: const Constant('{}'),
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    migrationRunId,
    conversationId,
    sourceEntityId,
    kind,
    severity,
    detailsJson,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'migration_issue_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  MigrationIssueRows createAlias(String alias) {
    return MigrationIssueRows(attachedDatabase, alias);
  }
}

class GenerationRunRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  GenerationRunRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> conversationId = GeneratedColumn<String>(
    'conversation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways(
      'REFERENCES conversation_rows (id) ON DELETE CASCADE',
    ),
  );
  late final GeneratedColumn<String> targetRevisionId = GeneratedColumn<String>(
    'target_revision_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> state = GeneratedColumn<String>(
    'state',
    aliasedName,
    false,
    check: () => state.isIn(const [
      'preparing',
      'requesting',
      'streaming',
      'waiting_tool',
      'completed',
      'failed',
      'cancelled',
      'interrupted',
    ]),
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> stateRevision = GeneratedColumn<int>(
    'state_revision',
    aliasedName,
    false,
    check: () => i2.ComparableExpr(stateRevision).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    defaultValue: const Constant(0),
  );
  late final GeneratedColumn<int> checkpointSeq = GeneratedColumn<int>(
    'checkpoint_seq',
    aliasedName,
    false,
    check: () => i2.ComparableExpr(checkpointSeq).isBiggerOrEqualValue(0),
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    defaultValue: const Constant(0),
  );
  late final GeneratedColumn<String> errorCode = GeneratedColumn<String>(
    'error_code',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> terminalAt = GeneratedColumn<int>(
    'terminal_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    conversationId,
    targetRevisionId,
    state,
    stateRevision,
    checkpointSeq,
    errorCode,
    createdAt,
    updatedAt,
    terminalAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'generation_run_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  GenerationRunRows createAlias(String alias) {
    return GenerationRunRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (target_revision_id) REFERENCES message_rows (id) DEFERRABLE INITIALLY DEFERRED',
    'CHECK (updated_at >= created_at)',
    'CHECK (terminal_at IS NULL OR terminal_at >= created_at)',
    'CHECK ((state IN (\'preparing\', \'requesting\', \'streaming\', \'waiting_tool\') AND terminal_at IS NULL) OR (state IN (\'completed\', \'failed\', \'cancelled\', \'interrupted\') AND terminal_at IS NOT NULL))',
    'CHECK (error_code IS NULL OR (length(error_code) BETWEEN 1 AND 128 AND state IN (\'failed\', \'cancelled\', \'interrupted\')))',
  ];
}

class E2eeSyncRecordStateRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  E2eeSyncRecordStateRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i3.Uint8List> digest =
      GeneratedColumn<i3.Uint8List>(
        'digest',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
      );
  late final GeneratedColumn<String> recordId = GeneratedColumn<String>(
    'record_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> entityType = GeneratedColumn<String>(
    'entity_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> entityId = GeneratedColumn<String>(
    'entity_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> logicalVersion = GeneratedColumn<int>(
    'logical_version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> kind = GeneratedColumn<String>(
    'kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> operationId = GeneratedColumn<String>(
    'operation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> claimedWriterDeviceId =
      GeneratedColumn<String>(
        'claimed_writer_device_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
      );
  late final GeneratedColumn<int> claimedWriterKeyVersion =
      GeneratedColumn<int>(
        'claimed_writer_key_version',
        aliasedName,
        false,
        type: DriftSqlType.int,
        requiredDuringInsert: true,
      );
  late final GeneratedColumn<int> keyEpoch = GeneratedColumn<int>(
    'key_epoch',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> acceptedAt = GeneratedColumn<int>(
    'accepted_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    digest,
    recordId,
    entityType,
    entityId,
    logicalVersion,
    kind,
    operationId,
    claimedWriterDeviceId,
    claimedWriterKeyVersion,
    keyEpoch,
    acceptedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'e2ee_sync_record_state_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {digest};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {operationId},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  E2eeSyncRecordStateRows createAlias(String alias) {
    return E2eeSyncRecordStateRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'CHECK (typeof(digest) = \'blob\' AND length(digest) = 32)',
    'CHECK (typeof(record_id) = \'text\' AND length(record_id) = 36 AND record_id = lower(record_id) AND record_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(record_id, 9, 1) = \'-\' AND substr(record_id, 14, 1) = \'-\' AND substr(record_id, 15, 1) = \'4\' AND substr(record_id, 19, 1) = \'-\' AND substr(record_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(record_id, 24, 1) = \'-\' AND substr(record_id, 1, 8) NOT GLOB \'*-*\' AND substr(record_id, 10, 4) NOT GLOB \'*-*\' AND substr(record_id, 15, 4) NOT GLOB \'*-*\' AND substr(record_id, 20, 4) NOT GLOB \'*-*\' AND substr(record_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(entity_type) = \'text\' AND length(CAST(entity_type AS BLOB)) BETWEEN 1 AND 64)',
    'CHECK (typeof(entity_id) = \'text\' AND length(CAST(entity_id AS BLOB)) BETWEEN 1 AND 1024)',
    'CHECK (typeof(logical_version) = \'integer\' AND logical_version BETWEEN 1 AND 9223372036854775807)',
    'CHECK (typeof(kind) = \'text\' AND kind IN (\'value\', \'tombstone\'))',
    'CHECK (typeof(operation_id) = \'text\' AND length(operation_id) = 36 AND operation_id = lower(operation_id) AND operation_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(operation_id, 9, 1) = \'-\' AND substr(operation_id, 14, 1) = \'-\' AND substr(operation_id, 15, 1) = \'4\' AND substr(operation_id, 19, 1) = \'-\' AND substr(operation_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(operation_id, 24, 1) = \'-\' AND substr(operation_id, 1, 8) NOT GLOB \'*-*\' AND substr(operation_id, 10, 4) NOT GLOB \'*-*\' AND substr(operation_id, 15, 4) NOT GLOB \'*-*\' AND substr(operation_id, 20, 4) NOT GLOB \'*-*\' AND substr(operation_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(claimed_writer_device_id) = \'text\' AND length(claimed_writer_device_id) = 36 AND claimed_writer_device_id = lower(claimed_writer_device_id) AND claimed_writer_device_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(claimed_writer_device_id, 9, 1) = \'-\' AND substr(claimed_writer_device_id, 14, 1) = \'-\' AND substr(claimed_writer_device_id, 15, 1) = \'4\' AND substr(claimed_writer_device_id, 19, 1) = \'-\' AND substr(claimed_writer_device_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(claimed_writer_device_id, 24, 1) = \'-\' AND substr(claimed_writer_device_id, 1, 8) NOT GLOB \'*-*\' AND substr(claimed_writer_device_id, 10, 4) NOT GLOB \'*-*\' AND substr(claimed_writer_device_id, 15, 4) NOT GLOB \'*-*\' AND substr(claimed_writer_device_id, 20, 4) NOT GLOB \'*-*\' AND substr(claimed_writer_device_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(claimed_writer_key_version) = \'integer\' AND claimed_writer_key_version BETWEEN 1 AND 4294967295)',
    'CHECK (typeof(key_epoch) = \'integer\' AND key_epoch BETWEEN 1 AND 2147483647)',
    'CHECK (typeof(accepted_at) = \'integer\' AND accepted_at >= 0)',
  ];
}

class E2eeSyncRecordParentRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  E2eeSyncRecordParentRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i3.Uint8List> childDigest =
      GeneratedColumn<i3.Uint8List>(
        'child_digest',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        defaultConstraints: GeneratedColumn.constraintIsAlways(
          'REFERENCES e2ee_sync_record_state_rows (digest) ON DELETE CASCADE',
        ),
      );
  late final GeneratedColumn<int> ordinal = GeneratedColumn<int>(
    'ordinal',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<i3.Uint8List> parentDigest =
      GeneratedColumn<i3.Uint8List>(
        'parent_digest',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        defaultConstraints: GeneratedColumn.constraintIsAlways(
          'REFERENCES e2ee_sync_record_state_rows (digest)',
        ),
      );
  @override
  List<GeneratedColumn> get $columns => [childDigest, ordinal, parentDigest];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'e2ee_sync_record_parent_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {childDigest, ordinal};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {childDigest, parentDigest},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  E2eeSyncRecordParentRows createAlias(String alias) {
    return E2eeSyncRecordParentRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'CHECK (typeof(child_digest) = \'blob\' AND length(child_digest) = 32)',
    'CHECK (typeof(ordinal) = \'integer\' AND ordinal BETWEEN 0 AND 1)',
    'CHECK (typeof(parent_digest) = \'blob\' AND length(parent_digest) = 32)',
    'CHECK (child_digest <> parent_digest)',
  ];
}

class E2eeSyncRecordHeadRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  E2eeSyncRecordHeadRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<i3.Uint8List> digest =
      GeneratedColumn<i3.Uint8List>(
        'digest',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        defaultConstraints: GeneratedColumn.constraintIsAlways(
          'REFERENCES e2ee_sync_record_state_rows (digest) ON DELETE CASCADE',
        ),
      );
  @override
  List<GeneratedColumn> get $columns => [digest];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'e2ee_sync_record_head_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {digest};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  E2eeSyncRecordHeadRows createAlias(String alias) {
    return E2eeSyncRecordHeadRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'CHECK (typeof(digest) = \'blob\' AND length(digest) = 32)',
  ];
}

class E2eeSyncIntentRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  E2eeSyncIntentRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> entityType = GeneratedColumn<String>(
    'entity_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> entityId = GeneratedColumn<String>(
    'entity_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> intentId = GeneratedColumn<String>(
    'intent_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> generation = GeneratedColumn<int>(
    'generation',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> phase = GeneratedColumn<String>(
    'phase',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> writerSessionId = GeneratedColumn<String>(
    'writer_session_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> sealLeaseToken = GeneratedColumn<String>(
    'seal_lease_token',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> sealOwnerSessionId =
      GeneratedColumn<String>(
        'seal_owner_session_id',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
      );
  late final GeneratedColumn<int> sealLeaseExpiresAt = GeneratedColumn<int>(
    'seal_lease_expires_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    entityType,
    entityId,
    intentId,
    generation,
    phase,
    writerSessionId,
    sealLeaseToken,
    sealOwnerSessionId,
    sealLeaseExpiresAt,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'e2ee_sync_intent_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {entityType, entityId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {intentId},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  E2eeSyncIntentRows createAlias(String alias) {
    return E2eeSyncIntentRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'CHECK (typeof(entity_type) = \'text\' AND length(CAST(entity_type AS BLOB)) BETWEEN 1 AND 64)',
    'CHECK (typeof(entity_id) = \'text\' AND length(CAST(entity_id AS BLOB)) BETWEEN 1 AND 1024)',
    'CHECK (typeof(intent_id) = \'text\' AND length(intent_id) = 36 AND intent_id = lower(intent_id) AND intent_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(intent_id, 9, 1) = \'-\' AND substr(intent_id, 14, 1) = \'-\' AND substr(intent_id, 15, 1) = \'4\' AND substr(intent_id, 19, 1) = \'-\' AND substr(intent_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(intent_id, 24, 1) = \'-\' AND substr(intent_id, 1, 8) NOT GLOB \'*-*\' AND substr(intent_id, 10, 4) NOT GLOB \'*-*\' AND substr(intent_id, 15, 4) NOT GLOB \'*-*\' AND substr(intent_id, 20, 4) NOT GLOB \'*-*\' AND substr(intent_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(generation) = \'integer\' AND generation BETWEEN 1 AND 9223372036854775807)',
    'CHECK (typeof(phase) = \'text\' AND phase IN (\'preparing\', \'dirty\', \'sealing\'))',
    'CHECK ((phase = \'preparing\' AND typeof(writer_session_id) = \'text\' AND length(CAST(writer_session_id AS BLOB)) >= 1 AND seal_lease_token IS NULL AND seal_owner_session_id IS NULL AND seal_lease_expires_at IS NULL) OR (phase = \'dirty\' AND writer_session_id IS NULL AND seal_lease_token IS NULL AND seal_owner_session_id IS NULL AND seal_lease_expires_at IS NULL) OR (phase = \'sealing\' AND writer_session_id IS NULL AND typeof(seal_lease_token) = \'text\' AND length(CAST(seal_lease_token AS BLOB)) >= 1 AND typeof(seal_owner_session_id) = \'text\' AND length(CAST(seal_owner_session_id AS BLOB)) >= 1 AND typeof(seal_lease_expires_at) = \'integer\' AND seal_lease_expires_at >= 0))',
    'CHECK (typeof(created_at) = \'integer\' AND created_at >= 0)',
    'CHECK (typeof(updated_at) = \'integer\' AND updated_at >= created_at)',
  ];
}

class E2eeSyncOperationRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  E2eeSyncOperationRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> operationId = GeneratedColumn<String>(
    'operation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<i3.Uint8List> stateDigest =
      GeneratedColumn<i3.Uint8List>(
        'state_digest',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
      );
  late final GeneratedColumn<String> recordId = GeneratedColumn<String>(
    'record_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> entityType = GeneratedColumn<String>(
    'entity_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> entityId = GeneratedColumn<String>(
    'entity_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> intentId = GeneratedColumn<String>(
    'intent_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> intentGeneration = GeneratedColumn<int>(
    'intent_generation',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> expectedRevision = GeneratedColumn<int>(
    'expected_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> accountUserId = GeneratedColumn<String>(
    'account_user_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> actorDeviceId = GeneratedColumn<String>(
    'actor_device_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> claimedWriterKeyVersion =
      GeneratedColumn<int>(
        'claimed_writer_key_version',
        aliasedName,
        false,
        type: DriftSqlType.int,
        requiredDuringInsert: true,
      );
  late final GeneratedColumn<String> outcome = GeneratedColumn<String>(
    'outcome',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> resultRevision = GeneratedColumn<int>(
    'result_revision',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> resultChangeSeq = GeneratedColumn<int>(
    'result_change_seq',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> currentRevision = GeneratedColumn<int>(
    'current_revision',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> errorCode = GeneratedColumn<String>(
    'error_code',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    operationId,
    stateDigest,
    recordId,
    entityType,
    entityId,
    intentId,
    intentGeneration,
    expectedRevision,
    accountUserId,
    actorDeviceId,
    claimedWriterKeyVersion,
    outcome,
    resultRevision,
    resultChangeSeq,
    currentRevision,
    errorCode,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'e2ee_sync_operation_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {operationId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {stateDigest},
    {operationId, recordId},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  E2eeSyncOperationRows createAlias(String alias) {
    return E2eeSyncOperationRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'CHECK (typeof(operation_id) = \'text\' AND length(operation_id) = 36 AND operation_id = lower(operation_id) AND operation_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(operation_id, 9, 1) = \'-\' AND substr(operation_id, 14, 1) = \'-\' AND substr(operation_id, 15, 1) = \'4\' AND substr(operation_id, 19, 1) = \'-\' AND substr(operation_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(operation_id, 24, 1) = \'-\' AND substr(operation_id, 1, 8) NOT GLOB \'*-*\' AND substr(operation_id, 10, 4) NOT GLOB \'*-*\' AND substr(operation_id, 15, 4) NOT GLOB \'*-*\' AND substr(operation_id, 20, 4) NOT GLOB \'*-*\' AND substr(operation_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(state_digest) = \'blob\' AND length(state_digest) = 32)',
    'CHECK (typeof(record_id) = \'text\' AND length(record_id) = 36 AND record_id = lower(record_id) AND record_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(record_id, 9, 1) = \'-\' AND substr(record_id, 14, 1) = \'-\' AND substr(record_id, 15, 1) = \'4\' AND substr(record_id, 19, 1) = \'-\' AND substr(record_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(record_id, 24, 1) = \'-\' AND substr(record_id, 1, 8) NOT GLOB \'*-*\' AND substr(record_id, 10, 4) NOT GLOB \'*-*\' AND substr(record_id, 15, 4) NOT GLOB \'*-*\' AND substr(record_id, 20, 4) NOT GLOB \'*-*\' AND substr(record_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(entity_type) = \'text\' AND length(CAST(entity_type AS BLOB)) BETWEEN 1 AND 64)',
    'CHECK (typeof(entity_id) = \'text\' AND length(CAST(entity_id AS BLOB)) BETWEEN 1 AND 1024)',
    'CHECK (typeof(intent_id) = \'text\' AND length(intent_id) = 36 AND intent_id = lower(intent_id) AND intent_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(intent_id, 9, 1) = \'-\' AND substr(intent_id, 14, 1) = \'-\' AND substr(intent_id, 15, 1) = \'4\' AND substr(intent_id, 19, 1) = \'-\' AND substr(intent_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(intent_id, 24, 1) = \'-\' AND substr(intent_id, 1, 8) NOT GLOB \'*-*\' AND substr(intent_id, 10, 4) NOT GLOB \'*-*\' AND substr(intent_id, 15, 4) NOT GLOB \'*-*\' AND substr(intent_id, 20, 4) NOT GLOB \'*-*\' AND substr(intent_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(intent_generation) = \'integer\' AND intent_generation BETWEEN 1 AND 9223372036854775807)',
    'CHECK (typeof(expected_revision) = \'integer\' AND expected_revision BETWEEN 0 AND 9223372036854775807)',
    'CHECK (typeof(account_user_id) = \'text\' AND length(account_user_id) = 36 AND account_user_id = lower(account_user_id) AND account_user_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(account_user_id, 9, 1) = \'-\' AND substr(account_user_id, 14, 1) = \'-\' AND substr(account_user_id, 15, 1) = \'4\' AND substr(account_user_id, 19, 1) = \'-\' AND substr(account_user_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(account_user_id, 24, 1) = \'-\' AND substr(account_user_id, 1, 8) NOT GLOB \'*-*\' AND substr(account_user_id, 10, 4) NOT GLOB \'*-*\' AND substr(account_user_id, 15, 4) NOT GLOB \'*-*\' AND substr(account_user_id, 20, 4) NOT GLOB \'*-*\' AND substr(account_user_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(actor_device_id) = \'text\' AND length(actor_device_id) = 36 AND actor_device_id = lower(actor_device_id) AND actor_device_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(actor_device_id, 9, 1) = \'-\' AND substr(actor_device_id, 14, 1) = \'-\' AND substr(actor_device_id, 15, 1) = \'4\' AND substr(actor_device_id, 19, 1) = \'-\' AND substr(actor_device_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(actor_device_id, 24, 1) = \'-\' AND substr(actor_device_id, 1, 8) NOT GLOB \'*-*\' AND substr(actor_device_id, 10, 4) NOT GLOB \'*-*\' AND substr(actor_device_id, 15, 4) NOT GLOB \'*-*\' AND substr(actor_device_id, 20, 4) NOT GLOB \'*-*\' AND substr(actor_device_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(claimed_writer_key_version) = \'integer\' AND claimed_writer_key_version BETWEEN 1 AND 4294967295)',
    'CHECK (typeof(outcome) = \'text\' AND outcome IN (\'active\', \'applied\', \'conflict\', \'rejected\'))',
    'CHECK (result_revision IS NULL OR (typeof(result_revision) = \'integer\' AND result_revision >= 1))',
    'CHECK (result_change_seq IS NULL OR (typeof(result_change_seq) = \'integer\' AND result_change_seq >= 0))',
    'CHECK (current_revision IS NULL OR (typeof(current_revision) = \'integer\' AND current_revision >= 1))',
    'CHECK (error_code IS NULL OR (typeof(error_code) = \'text\' AND length(CAST(error_code AS BLOB)) BETWEEN 1 AND 100))',
    'CHECK ((outcome = \'active\' AND result_revision IS NULL AND result_change_seq IS NULL AND current_revision IS NULL AND error_code IS NULL) OR (outcome = \'applied\' AND result_revision IS NOT NULL AND result_change_seq IS NOT NULL AND current_revision IS NULL AND error_code IS NULL) OR (outcome = \'conflict\' AND result_revision IS NULL AND result_change_seq IS NULL AND error_code IS NULL) OR (outcome = \'rejected\' AND result_revision IS NULL AND result_change_seq IS NULL AND current_revision IS NULL AND error_code IS NOT NULL))',
    'CHECK (typeof(created_at) = \'integer\' AND created_at >= 0)',
    'CHECK (typeof(updated_at) = \'integer\' AND updated_at >= created_at)',
  ];
}

class E2eeSyncOutboxRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  E2eeSyncOutboxRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> operationId = GeneratedColumn<String>(
    'operation_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> recordId = GeneratedColumn<String>(
    'record_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> envelopeVersion = GeneratedColumn<int>(
    'envelope_version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> keyEpoch = GeneratedColumn<int>(
    'key_epoch',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<i3.Uint8List> ciphertext =
      GeneratedColumn<i3.Uint8List>(
        'ciphertext',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
      );
  late final GeneratedColumn<String> phase = GeneratedColumn<String>(
    'phase',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> leaseToken = GeneratedColumn<String>(
    'lease_token',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> leaseOwnerSessionId =
      GeneratedColumn<String>(
        'lease_owner_session_id',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
      );
  late final GeneratedColumn<int> leaseExpiresAt = GeneratedColumn<int>(
    'lease_expires_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> transitionVersion = GeneratedColumn<int>(
    'transition_version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> attemptCount = GeneratedColumn<int>(
    'attempt_count',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> nextAttemptAt = GeneratedColumn<int>(
    'next_attempt_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<String> lastFailureKind = GeneratedColumn<String>(
    'last_failure_kind',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    operationId,
    recordId,
    envelopeVersion,
    keyEpoch,
    ciphertext,
    phase,
    leaseToken,
    leaseOwnerSessionId,
    leaseExpiresAt,
    transitionVersion,
    attemptCount,
    nextAttemptAt,
    lastFailureKind,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'e2ee_sync_outbox_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {operationId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {recordId},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  E2eeSyncOutboxRows createAlias(String alias) {
    return E2eeSyncOutboxRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'FOREIGN KEY (operation_id, record_id) REFERENCES e2ee_sync_operation_rows (operation_id, record_id)',
    'CHECK (typeof(operation_id) = \'text\' AND length(operation_id) = 36 AND operation_id = lower(operation_id) AND operation_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(operation_id, 9, 1) = \'-\' AND substr(operation_id, 14, 1) = \'-\' AND substr(operation_id, 15, 1) = \'4\' AND substr(operation_id, 19, 1) = \'-\' AND substr(operation_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(operation_id, 24, 1) = \'-\' AND substr(operation_id, 1, 8) NOT GLOB \'*-*\' AND substr(operation_id, 10, 4) NOT GLOB \'*-*\' AND substr(operation_id, 15, 4) NOT GLOB \'*-*\' AND substr(operation_id, 20, 4) NOT GLOB \'*-*\' AND substr(operation_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(record_id) = \'text\' AND length(record_id) = 36 AND record_id = lower(record_id) AND record_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(record_id, 9, 1) = \'-\' AND substr(record_id, 14, 1) = \'-\' AND substr(record_id, 15, 1) = \'4\' AND substr(record_id, 19, 1) = \'-\' AND substr(record_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(record_id, 24, 1) = \'-\' AND substr(record_id, 1, 8) NOT GLOB \'*-*\' AND substr(record_id, 10, 4) NOT GLOB \'*-*\' AND substr(record_id, 15, 4) NOT GLOB \'*-*\' AND substr(record_id, 20, 4) NOT GLOB \'*-*\' AND substr(record_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (typeof(envelope_version) = \'integer\' AND envelope_version = 1)',
    'CHECK (typeof(key_epoch) = \'integer\' AND key_epoch BETWEEN 1 AND 2147483647)',
    'CHECK (typeof(ciphertext) = \'blob\' AND length(ciphertext) BETWEEN 1 AND 1048576)',
    'CHECK (typeof(phase) = \'text\' AND phase IN (\'ready\', \'sending\'))',
    'CHECK ((phase = \'ready\' AND lease_token IS NULL AND lease_owner_session_id IS NULL AND lease_expires_at IS NULL) OR (phase = \'sending\' AND typeof(lease_token) = \'text\' AND length(CAST(lease_token AS BLOB)) >= 1 AND typeof(lease_owner_session_id) = \'text\' AND length(CAST(lease_owner_session_id AS BLOB)) >= 1 AND typeof(lease_expires_at) = \'integer\' AND lease_expires_at >= 0))',
    'CHECK (typeof(transition_version) = \'integer\' AND transition_version BETWEEN 1 AND 9223372036854775807)',
    'CHECK (typeof(attempt_count) = \'integer\' AND attempt_count >= 0)',
    'CHECK (typeof(next_attempt_at) = \'integer\' AND next_attempt_at >= 0)',
    'CHECK (last_failure_kind IS NULL OR (typeof(last_failure_kind) = \'text\' AND length(CAST(last_failure_kind AS BLOB)) BETWEEN 1 AND 100))',
    'CHECK (typeof(created_at) = \'integer\' AND created_at >= 0)',
    'CHECK (typeof(updated_at) = \'integer\' AND updated_at >= created_at)',
  ];
}

class E2eeSyncRemoteRecordRows extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  E2eeSyncRemoteRecordRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> recordId = GeneratedColumn<String>(
    'record_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> revision = GeneratedColumn<int>(
    'revision',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> lastChangeSeq = GeneratedColumn<int>(
    'last_change_seq',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<i3.Uint8List> stateDigest =
      GeneratedColumn<i3.Uint8List>(
        'state_digest',
        aliasedName,
        true,
        type: DriftSqlType.blob,
        requiredDuringInsert: false,
      );
  late final GeneratedColumn<String> gate = GeneratedColumn<String>(
    'gate',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> observedRevision = GeneratedColumn<int>(
    'observed_revision',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<String> errorCode = GeneratedColumn<String>(
    'error_code',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  late final GeneratedColumn<int> updatedAt = GeneratedColumn<int>(
    'updated_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
  );
  @override
  List<GeneratedColumn> get $columns => [
    recordId,
    revision,
    lastChangeSeq,
    stateDigest,
    gate,
    observedRevision,
    errorCode,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'e2ee_sync_remote_record_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {recordId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  E2eeSyncRemoteRecordRows createAlias(String alias) {
    return E2eeSyncRemoteRecordRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'CHECK (typeof(record_id) = \'text\' AND length(record_id) = 36 AND record_id = lower(record_id) AND record_id NOT GLOB \'*[^0-9a-f-]*\' AND substr(record_id, 9, 1) = \'-\' AND substr(record_id, 14, 1) = \'-\' AND substr(record_id, 15, 1) = \'4\' AND substr(record_id, 19, 1) = \'-\' AND substr(record_id, 20, 1) IN (\'8\', \'9\', \'a\', \'b\') AND substr(record_id, 24, 1) = \'-\' AND substr(record_id, 1, 8) NOT GLOB \'*-*\' AND substr(record_id, 10, 4) NOT GLOB \'*-*\' AND substr(record_id, 15, 4) NOT GLOB \'*-*\' AND substr(record_id, 20, 4) NOT GLOB \'*-*\' AND substr(record_id, 25, 12) NOT GLOB \'*-*\')',
    'CHECK (revision IS NULL OR (typeof(revision) = \'integer\' AND revision >= 1))',
    'CHECK (last_change_seq IS NULL OR (typeof(last_change_seq) = \'integer\' AND last_change_seq >= 0))',
    'CHECK (state_digest IS NULL OR (typeof(state_digest) = \'blob\' AND length(state_digest) = 32))',
    'CHECK ((revision IS NULL AND last_change_seq IS NULL AND state_digest IS NULL) OR (revision IS NOT NULL AND last_change_seq IS NOT NULL AND state_digest IS NOT NULL))',
    'CHECK (typeof(gate) = \'text\' AND gate IN (\'ready\', \'requires-pull\', \'quarantined\'))',
    'CHECK (observed_revision IS NULL OR (typeof(observed_revision) = \'integer\' AND observed_revision >= 1))',
    'CHECK (error_code IS NULL OR (typeof(error_code) = \'text\' AND length(CAST(error_code AS BLOB)) BETWEEN 1 AND 100))',
    'CHECK ((gate = \'ready\' AND observed_revision IS NULL AND error_code IS NULL) OR (gate = \'requires-pull\' AND error_code IS NULL) OR (gate = \'quarantined\' AND error_code IS NOT NULL))',
    'CHECK (typeof(created_at) = \'integer\' AND created_at >= 0)',
    'CHECK (typeof(updated_at) = \'integer\' AND updated_at >= created_at)',
  ];
}

class DatabaseAtV14 extends GeneratedDatabase {
  DatabaseAtV14(QueryExecutor e) : super(e);
  late final ConversationRows conversationRows = ConversationRows(this);
  late final MessageRows messageRows = MessageRows(this);
  late final TurnRows turnRows = TurnRows(this);
  late final ConversationMcpServerRows conversationMcpServerRows =
      ConversationMcpServerRows(this);
  late final ToolEventRows toolEventRows = ToolEventRows(this);
  late final GeminiThoughtSignatureRows geminiThoughtSignatureRows =
      GeminiThoughtSignatureRows(this);
  late final ChatStorageMetaRows chatStorageMetaRows = ChatStorageMetaRows(
    this,
  );
  late final MessagePartRows messagePartRows = MessagePartRows(this);
  late final ProviderArtifactRows providerArtifactRows = ProviderArtifactRows(
    this,
  );
  late final MigrationRunRows migrationRunRows = MigrationRunRows(this);
  late final MigrationIssueRows migrationIssueRows = MigrationIssueRows(this);
  late final GenerationRunRows generationRunRows = GenerationRunRows(this);
  late final E2eeSyncRecordStateRows e2eeSyncRecordStateRows =
      E2eeSyncRecordStateRows(this);
  late final E2eeSyncRecordParentRows e2eeSyncRecordParentRows =
      E2eeSyncRecordParentRows(this);
  late final E2eeSyncRecordHeadRows e2eeSyncRecordHeadRows =
      E2eeSyncRecordHeadRows(this);
  late final E2eeSyncIntentRows e2eeSyncIntentRows = E2eeSyncIntentRows(this);
  late final E2eeSyncOperationRows e2eeSyncOperationRows =
      E2eeSyncOperationRows(this);
  late final E2eeSyncOutboxRows e2eeSyncOutboxRows = E2eeSyncOutboxRows(this);
  late final E2eeSyncRemoteRecordRows e2eeSyncRemoteRecordRows =
      E2eeSyncRemoteRecordRows(this);
  late final Index idxConversationsUpdatedAt = Index(
    'idx_conversations_updated_at',
    'CREATE INDEX idx_conversations_updated_at ON conversation_rows (updated_at DESC, id ASC)',
  );
  late final Index idxConversationsAssistant = Index(
    'idx_conversations_assistant',
    'CREATE INDEX idx_conversations_assistant ON conversation_rows (assistant_id)',
  );
  late final Index idxMessagesConversationOrder = Index(
    'idx_messages_conversation_order',
    'CREATE INDEX idx_messages_conversation_order ON message_rows (conversation_id, message_order, id)',
  );
  late final Index idxMessagesConversationTimestamp = Index(
    'idx_messages_conversation_timestamp',
    'CREATE INDEX idx_messages_conversation_timestamp ON message_rows (conversation_id, timestamp, id)',
  );
  late final Index idxMessagesGroup = Index(
    'idx_messages_group',
    'CREATE INDEX idx_messages_group ON message_rows (conversation_id, group_id, version, id)',
  );
  late final Index idxMessagesTurn = Index(
    'idx_messages_turn',
    'CREATE INDEX idx_messages_turn ON message_rows (conversation_id, turn_id, message_order, id)',
  );
  late final Index idxTurnsConversationCreated = Index(
    'idx_turns_conversation_created',
    'CREATE INDEX idx_turns_conversation_created ON turn_rows (conversation_id, created_at, id)',
  );
  late final Index idxMessagePartsRevisionOrdinal = Index(
    'idx_message_parts_revision_ordinal',
    'CREATE INDEX idx_message_parts_revision_ordinal ON message_part_rows (conversation_id, revision_id, ordinal)',
  );
  late final Index idxProviderArtifactsRevisionKind = Index(
    'idx_provider_artifacts_revision_kind',
    'CREATE INDEX idx_provider_artifacts_revision_kind ON provider_artifact_rows (conversation_id, revision_id, kind)',
  );
  late final Index idxMigrationIssuesRunKind = Index(
    'idx_migration_issues_run_kind',
    'CREATE INDEX idx_migration_issues_run_kind ON migration_issue_rows (migration_run_id, kind, id)',
  );
  late final Index idxGenerationRunsActiveTarget = Index(
    'idx_generation_runs_active_target',
    'CREATE UNIQUE INDEX idx_generation_runs_active_target ON generation_run_rows (conversation_id, target_revision_id) WHERE state IN (\'preparing\', \'requesting\', \'streaming\', \'waiting_tool\')',
  );
  late final Index idxGenerationRunsStateUpdated = Index(
    'idx_generation_runs_state_updated',
    'CREATE INDEX idx_generation_runs_state_updated ON generation_run_rows (state, updated_at, id)',
  );
  late final Index idxE2eeSyncRecordStatesRecordVersion = Index(
    'idx_e2ee_sync_record_states_record_version',
    'CREATE INDEX idx_e2ee_sync_record_states_record_version ON e2ee_sync_record_state_rows (record_id, logical_version, digest)',
  );
  late final Index idxE2eeSyncIntentsPhaseUpdated = Index(
    'idx_e2ee_sync_intents_phase_updated',
    'CREATE INDEX idx_e2ee_sync_intents_phase_updated ON e2ee_sync_intent_rows (phase, updated_at, entity_type, entity_id)',
  );
  late final Index idxE2eeSyncOperationsEntityGeneration = Index(
    'idx_e2ee_sync_operations_entity_generation',
    'CREATE INDEX idx_e2ee_sync_operations_entity_generation ON e2ee_sync_operation_rows (entity_type, entity_id, intent_generation, operation_id)',
  );
  late final Index idxE2eeSyncOperationsIntentGeneration = Index(
    'idx_e2ee_sync_operations_intent_generation',
    'CREATE INDEX idx_e2ee_sync_operations_intent_generation ON e2ee_sync_operation_rows (intent_id, intent_generation, operation_id)',
  );
  late final Index idxE2eeSyncOutboxPhaseDue = Index(
    'idx_e2ee_sync_outbox_phase_due',
    'CREATE INDEX idx_e2ee_sync_outbox_phase_due ON e2ee_sync_outbox_rows (phase, next_attempt_at, operation_id)',
  );
  late final Index idxE2eeSyncRemoteRecordsGateUpdated = Index(
    'idx_e2ee_sync_remote_records_gate_updated',
    'CREATE INDEX idx_e2ee_sync_remote_records_gate_updated ON e2ee_sync_remote_record_rows (gate, updated_at, record_id)',
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    conversationRows,
    messageRows,
    turnRows,
    conversationMcpServerRows,
    toolEventRows,
    geminiThoughtSignatureRows,
    chatStorageMetaRows,
    messagePartRows,
    providerArtifactRows,
    migrationRunRows,
    migrationIssueRows,
    generationRunRows,
    e2eeSyncRecordStateRows,
    e2eeSyncRecordParentRows,
    e2eeSyncRecordHeadRows,
    e2eeSyncIntentRows,
    e2eeSyncOperationRows,
    e2eeSyncOutboxRows,
    e2eeSyncRemoteRecordRows,
    idxConversationsUpdatedAt,
    idxConversationsAssistant,
    idxMessagesConversationOrder,
    idxMessagesConversationTimestamp,
    idxMessagesGroup,
    idxMessagesTurn,
    idxTurnsConversationCreated,
    idxMessagePartsRevisionOrdinal,
    idxProviderArtifactsRevisionKind,
    idxMigrationIssuesRunKind,
    idxGenerationRunsActiveTarget,
    idxGenerationRunsStateUpdated,
    idxE2eeSyncRecordStatesRecordVersion,
    idxE2eeSyncIntentsPhaseUpdated,
    idxE2eeSyncOperationsEntityGeneration,
    idxE2eeSyncOperationsIntentGeneration,
    idxE2eeSyncOutboxPhaseDue,
    idxE2eeSyncRemoteRecordsGateUpdated,
  ];
  @override
  int get schemaVersion => 14;
}
