// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Uint32 Function()>()
external int kelivo_core_abi_version();

@ffi.Native<
  KelivoStatus Function(ffi.Pointer<KelivoCoreCapabilities>, ffi.Size)
>()
external int kelivo_core_get_capabilities(
  ffi.Pointer<KelivoCoreCapabilities> out_capabilities,
  int out_capabilities_size,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint64>,
  )
>()
external int kelivo_key_slot_create(
  ffi.Pointer<ffi.Uint8> slot_id,
  int slot_id_length,
  int policy_version,
  ffi.Pointer<ffi.Uint64> out_handle,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint64>,
  )
>()
external int kelivo_key_slot_open(
  ffi.Pointer<ffi.Uint8> slot_id,
  int slot_id_length,
  int policy_version,
  ffi.Pointer<ffi.Uint64> out_handle,
);

@ffi.Native<KelivoStatus Function(ffi.Uint64)>()
external int kelivo_key_handle_close(int handle);

typedef KelivoStatus = ffi.Int32;
typedef DartKelivoStatus = int;

final class KelivoCoreCapabilities extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint64()
  external int flags;

  @ffi.Uint32()
  external int secure_storage_backend;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Uint32> reserved;
}

const int KELIVO_CORE_ABI_VERSION = 1;

const int KELIVO_CORE_CAPABILITIES_STRUCT_SIZE = 32;

const int KELIVO_KEY_SLOT_ID_SIZE = 16;

const int KELIVO_KEY_POLICY_VERSION = 1;

const int KELIVO_INVALID_KEY_HANDLE = 0;

const int KELIVO_STATUS_OK = 0;

const int KELIVO_STATUS_NULL_POINTER = 1;

const int KELIVO_STATUS_INVALID_SLOT_ID_LENGTH = 2;

const int KELIVO_STATUS_UNSUPPORTED_POLICY = 3;

const int KELIVO_STATUS_INVALID_KEY_HANDLE = 4;

const int KELIVO_STATUS_OUTPUT_BUFFER_TOO_SMALL = 5;

const int KELIVO_STATUS_UNSUPPORTED_PLATFORM = 100;

const int KELIVO_SECURE_STORAGE_BACKEND_NONE = 0;

const int KELIVO_CAPABILITY_FLAGS_NONE = 0;
