// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Uint32 Function()>()
external int kelivo_core_abi_version();

@ffi.Native<
  KelivoStatus Function(ffi.Pointer<KelivoCoreCapabilities>, ffi.Size)
>()
external int kelivo_core_get_capabilities(
  ffi.Pointer<KelivoCoreCapabilities> out_capabilities,
  int out_capabilities_size,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint64>,
  )
>()
external int kelivo_key_slot_create(
  ffi.Pointer<ffi.Uint8> slot_id,
  int slot_id_length,
  int policy_version,
  ffi.Pointer<ffi.Uint64> out_handle,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint64>,
  )
>()
external int kelivo_key_slot_open(
  ffi.Pointer<ffi.Uint8> slot_id,
  int slot_id_length,
  int policy_version,
  ffi.Pointer<ffi.Uint64> out_handle,
);

@ffi.Native<KelivoStatus Function(ffi.Uint64)>()
external int kelivo_key_handle_close(int handle);

@ffi.Native<
  KelivoStatus Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Uint64,
    ffi.Pointer<ffi.Void>,
    KelivoSqlCipherKeyCallback,
  )
>()
external int kelivo_sqlcipher_key_apply(
  int handle,
  ffi.Pointer<ffi.Uint8> database_id,
  int database_id_length,
  int epoch,
  ffi.Pointer<ffi.Void> database,
  KelivoSqlCipherKeyCallback key_callback,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Uint64,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    KelivoSqlitePrepareCallback,
    KelivoSqliteBindTextCallback,
    KelivoSqliteBindBlobCallback,
    KelivoSqliteStepCallback,
    KelivoSqliteFinalizeCallback,
  )
>()
external int kelivo_sqlcipher_database_attach(
  int handle,
  ffi.Pointer<ffi.Uint8> database_id,
  int database_id_length,
  int epoch,
  ffi.Pointer<ffi.Void> database,
  ffi.Pointer<ffi.Uint8> database_path,
  int database_path_length,
  ffi.Pointer<ffi.Uint8> database_name,
  int database_name_length,
  KelivoSqlitePrepareCallback prepare_callback,
  KelivoSqliteBindTextCallback bind_text_callback,
  KelivoSqliteBindBlobCallback bind_blob_callback,
  KelivoSqliteStepCallback step_callback,
  KelivoSqliteFinalizeCallback finalize_callback,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int kelivo_record_seal(
  int handle,
  ffi.Pointer<ffi.Uint8> record_id,
  int record_id_length,
  int epoch,
  ffi.Pointer<ffi.Uint8> associated_data,
  int associated_data_length,
  ffi.Pointer<ffi.Uint8> plaintext,
  int plaintext_length,
  ffi.Pointer<ffi.Uint8> out_envelope,
  int out_envelope_capacity,
  ffi.Pointer<ffi.Size> out_envelope_length,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int kelivo_record_open(
  int handle,
  ffi.Pointer<ffi.Uint8> record_id,
  int record_id_length,
  int epoch,
  ffi.Pointer<ffi.Uint8> associated_data,
  int associated_data_length,
  ffi.Pointer<ffi.Uint8> envelope,
  int envelope_length,
  ffi.Pointer<ffi.Uint8> out_plaintext,
  int out_plaintext_capacity,
  ffi.Pointer<ffi.Size> out_plaintext_length,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint64>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int kelivo_opaque_client_registration_start(
  ffi.Pointer<ffi.Uint8> password,
  int password_length,
  ffi.Pointer<ffi.Uint64> out_state_handle,
  ffi.Pointer<ffi.Uint8> out_request,
  int out_request_capacity,
  ffi.Pointer<ffi.Size> out_request_length,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int kelivo_opaque_client_registration_finish(
  int state_handle,
  ffi.Pointer<ffi.Uint8> password,
  int password_length,
  ffi.Pointer<ffi.Uint8> response,
  int response_length,
  ffi.Pointer<ffi.Uint8> credential_identifier,
  int credential_identifier_length,
  ffi.Pointer<ffi.Uint8> out_upload,
  int out_upload_capacity,
  ffi.Pointer<ffi.Size> out_upload_length,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint64>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int kelivo_opaque_client_login_start(
  ffi.Pointer<ffi.Uint8> password,
  int password_length,
  ffi.Pointer<ffi.Uint64> out_state_handle,
  ffi.Pointer<ffi.Uint8> out_request,
  int out_request_capacity,
  ffi.Pointer<ffi.Size> out_request_length,
);

@ffi.Native<
  KelivoStatus Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int kelivo_opaque_client_login_finish(
  int state_handle,
  ffi.Pointer<ffi.Uint8> password,
  int password_length,
  ffi.Pointer<ffi.Uint8> response,
  int response_length,
  ffi.Pointer<ffi.Uint8> credential_identifier,
  int credential_identifier_length,
  ffi.Pointer<ffi.Uint8> out_finalization,
  int out_finalization_capacity,
  ffi.Pointer<ffi.Size> out_finalization_length,
);

@ffi.Native<KelivoStatus Function(ffi.Uint64)>()
external int kelivo_opaque_client_state_close(int state_handle);

typedef KelivoStatus = ffi.Int32;
typedef DartKelivoStatus = int;
typedef KelivoSqlCipherKeyCallbackFunction =
    ffi.Int32 Function(
      ffi.Pointer<ffi.Void> database,
      ffi.Pointer<ffi.Void> key,
      ffi.Int32 key_length,
    );
typedef DartKelivoSqlCipherKeyCallbackFunction =
    int Function(
      ffi.Pointer<ffi.Void> database,
      ffi.Pointer<ffi.Void> key,
      int key_length,
    );
typedef KelivoSqlCipherKeyCallback =
    ffi.Pointer<ffi.NativeFunction<KelivoSqlCipherKeyCallbackFunction>>;
typedef KelivoSqlitePrepareCallbackFunction =
    ffi.Int32 Function(
      ffi.Pointer<ffi.Void> database,
      ffi.Pointer<ffi.Char> sql,
      ffi.Int32 sql_length,
      ffi.Pointer<ffi.Pointer<ffi.Void>> out_statement,
      ffi.Pointer<ffi.Pointer<ffi.Char>> sql_tail,
    );
typedef DartKelivoSqlitePrepareCallbackFunction =
    int Function(
      ffi.Pointer<ffi.Void> database,
      ffi.Pointer<ffi.Char> sql,
      int sql_length,
      ffi.Pointer<ffi.Pointer<ffi.Void>> out_statement,
      ffi.Pointer<ffi.Pointer<ffi.Char>> sql_tail,
    );
typedef KelivoSqlitePrepareCallback =
    ffi.Pointer<ffi.NativeFunction<KelivoSqlitePrepareCallbackFunction>>;
typedef KelivoSqliteDestructorFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> value);
typedef DartKelivoSqliteDestructorFunction =
    void Function(ffi.Pointer<ffi.Void> value);
typedef KelivoSqliteDestructor =
    ffi.Pointer<ffi.NativeFunction<KelivoSqliteDestructorFunction>>;
typedef KelivoSqliteBindTextCallbackFunction =
    ffi.Int32 Function(
      ffi.Pointer<ffi.Void> statement,
      ffi.Int32 index,
      ffi.Pointer<ffi.Char> value,
      ffi.Int32 value_length,
      KelivoSqliteDestructor destructor,
    );
typedef DartKelivoSqliteBindTextCallbackFunction =
    int Function(
      ffi.Pointer<ffi.Void> statement,
      int index,
      ffi.Pointer<ffi.Char> value,
      int value_length,
      KelivoSqliteDestructor destructor,
    );
typedef KelivoSqliteBindTextCallback =
    ffi.Pointer<ffi.NativeFunction<KelivoSqliteBindTextCallbackFunction>>;
typedef KelivoSqliteBindBlobCallbackFunction =
    ffi.Int32 Function(
      ffi.Pointer<ffi.Void> statement,
      ffi.Int32 index,
      ffi.Pointer<ffi.Void> value,
      ffi.Int32 value_length,
      KelivoSqliteDestructor destructor,
    );
typedef DartKelivoSqliteBindBlobCallbackFunction =
    int Function(
      ffi.Pointer<ffi.Void> statement,
      int index,
      ffi.Pointer<ffi.Void> value,
      int value_length,
      KelivoSqliteDestructor destructor,
    );
typedef KelivoSqliteBindBlobCallback =
    ffi.Pointer<ffi.NativeFunction<KelivoSqliteBindBlobCallbackFunction>>;
typedef KelivoSqliteStepCallbackFunction =
    ffi.Int32 Function(ffi.Pointer<ffi.Void> statement);
typedef DartKelivoSqliteStepCallbackFunction =
    int Function(ffi.Pointer<ffi.Void> statement);
typedef KelivoSqliteStepCallback =
    ffi.Pointer<ffi.NativeFunction<KelivoSqliteStepCallbackFunction>>;
typedef KelivoSqliteFinalizeCallbackFunction =
    ffi.Int32 Function(ffi.Pointer<ffi.Void> statement);
typedef DartKelivoSqliteFinalizeCallbackFunction =
    int Function(ffi.Pointer<ffi.Void> statement);
typedef KelivoSqliteFinalizeCallback =
    ffi.Pointer<ffi.NativeFunction<KelivoSqliteFinalizeCallbackFunction>>;

final class KelivoCoreCapabilities extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint64()
  external int flags;

  @ffi.Uint32()
  external int secure_storage_backend;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Uint32> reserved;
}

const int KELIVO_CORE_ABI_VERSION = 3;

const int KELIVO_CORE_CAPABILITIES_STRUCT_SIZE = 32;

const int KELIVO_KEY_SLOT_ID_SIZE = 16;

const int KELIVO_KEY_POLICY_VERSION = 1;

const int KELIVO_INVALID_KEY_HANDLE = 0;

const int KELIVO_STATUS_OK = 0;

const int KELIVO_STATUS_NULL_POINTER = 1;

const int KELIVO_STATUS_INVALID_SLOT_ID_LENGTH = 2;

const int KELIVO_STATUS_UNSUPPORTED_POLICY = 3;

const int KELIVO_STATUS_INVALID_KEY_HANDLE = 4;

const int KELIVO_STATUS_OUTPUT_BUFFER_TOO_SMALL = 5;

const int KELIVO_STATUS_SLOT_NOT_FOUND = 6;

const int KELIVO_STATUS_SLOT_ALREADY_EXISTS = 7;

const int KELIVO_STATUS_SLOT_DATA_INVALID = 8;

const int KELIVO_STATUS_SLOT_UNWRAP_FAILED = 9;

const int KELIVO_STATUS_SECURE_STORAGE_UNAVAILABLE = 10;

const int KELIVO_STATUS_RANDOM_SOURCE_FAILURE = 11;

const int KELIVO_STATUS_IO_FAILURE = 12;

const int KELIVO_STATUS_INTERNAL_STATE = 13;

const int KELIVO_STATUS_INVALID_RECORD_ID_LENGTH = 14;

const int KELIVO_STATUS_INVALID_ARGUMENT = 15;

const int KELIVO_STATUS_RECORD_ENVELOPE_INVALID = 16;

const int KELIVO_STATUS_RECORD_AUTHENTICATION_FAILED = 17;

const int KELIVO_STATUS_INPUT_TOO_LARGE = 18;

const int KELIVO_STATUS_SQLCIPHER_KEY_FAILED = 19;

const int KELIVO_STATUS_SQLCIPHER_ATTACH_FAILED = 20;

const int KELIVO_STATUS_INVALID_OPAQUE_STATE_HANDLE = 21;

const int KELIVO_STATUS_OPAQUE_MESSAGE_INVALID = 22;

const int KELIVO_STATUS_OPAQUE_PROTOCOL_FAILED = 23;

const int KELIVO_STATUS_TOO_MANY_ACTIVE_HANDLES = 24;

const int KELIVO_STATUS_HANDLE_SPACE_EXHAUSTED = 25;

const int KELIVO_STATUS_INVALID_ACCOUNT_ID = 26;

const int KELIVO_STATUS_UNSUPPORTED_PLATFORM = 100;

const int KELIVO_SECURE_STORAGE_BACKEND_NONE = 0;

const int KELIVO_SECURE_STORAGE_BACKEND_WINDOWS_DPAPI = 1;

const int KELIVO_SECURE_STORAGE_BACKEND_ANDROID_KEYSTORE = 2;

const int KELIVO_SECURE_STORAGE_BACKEND_LINUX_SECRET_SERVICE = 3;

const int KELIVO_CAPABILITY_FLAGS_NONE = 0;

const int KELIVO_CAPABILITY_KEY_SLOTS = 1;

const int KELIVO_CAPABILITY_BACKGROUND_ACCESS = 2;

const int KELIVO_CAPABILITY_RECORD_ENVELOPES = 4;

const int KELIVO_CAPABILITY_SQLCIPHER_KEY_APPLICATION = 8;

const int KELIVO_CAPABILITY_SQLCIPHER_DATABASE_ATTACH = 16;

const int KELIVO_CAPABILITY_OPAQUE_CLIENT = 32;

const int KELIVO_RECORD_ID_SIZE = 16;

const int KELIVO_RECORD_MAX_ASSOCIATED_DATA_SIZE = 65536;

const int KELIVO_RECORD_MAX_PLAINTEXT_SIZE = 16777216;

const int KELIVO_RECORD_MAX_ENVELOPE_SIZE = 16777296;

const int KELIVO_DATABASE_ID_SIZE = 16;

const int KELIVO_DATABASE_NAME_MAX_SIZE = 64;

const int KELIVO_DATABASE_PATH_MAX_SIZE = 65536;

const int KELIVO_OPAQUE_INVALID_STATE_HANDLE = 0;

const int KELIVO_OPAQUE_MAX_INPUT_SIZE = 65535;

const int KELIVO_OPAQUE_ACCOUNT_ID_SIZE = 16;

const int KELIVO_OPAQUE_REGISTRATION_REQUEST_SIZE = 48;

const int KELIVO_OPAQUE_REGISTRATION_RESPONSE_SIZE = 80;

const int KELIVO_OPAQUE_REGISTRATION_UPLOAD_SIZE = 208;

const int KELIVO_OPAQUE_CREDENTIAL_REQUEST_SIZE = 112;

const int KELIVO_OPAQUE_CREDENTIAL_RESPONSE_SIZE = 336;

const int KELIVO_OPAQUE_CREDENTIAL_FINALIZATION_SIZE = 80;
